identity_txt_firstName = "//input[@name='first_name']"
identity_txt_lastName = "//input[@name='last_name']"
identity_txt_email = "//input[@name='email']"
identity_txt_birthday= "//input[@type='date']"
identity_txt_address = '//textarea[@name="address"]'
identity_txt_city = "//input[@name='city']"
identity_txt_state = "//input[@name='stateAbbr']"
identity_txt_zipcode = "//input[@name='zipcode']"
identity_txt_password = "//input[@name='password']"
identity_txt_confirm_password = "//input[@name='confirm_password']"
identity_btn_save = "//button[@aria-label='Save']"